project:
  type: website

website:
  title: "CHEESES"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plot2.qmd
      - href: plot3.qmd
      - about.qmd
      - href: sources.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



